/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package usuario;

import longin.logeo;

/**
 *
 * @author SENA
 */
public class ingresar extends javax.swing.JFrame {

    /**
     * Creates new form consulta
     */
    public ingresar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consultarhuella = new javax.swing.JButton();
        consultarman = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        consultarhuella.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        consultarhuella.setText("Consulta por Huella");
        consultarhuella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarhuellaActionPerformed(evt);
            }
        });

        consultarman.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        consultarman.setText("Consultar Manualmente");
        consultarman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarmanActionPerformed(evt);
            }
        });

        jButton1.setText("LOGEO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consultarman)
                    .addComponent(consultarhuella))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {consultarhuella, consultarman});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(consultarman, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(consultarhuella, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {consultarhuella, consultarman});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void consultarmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarmanActionPerformed
//       esta accion es para ver datos basicos de el usuario
        confirmar muestra = new confirmar();
        muestra.setVisible(true);
        
        
    }//GEN-LAST:event_consultarmanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        logeo log = new logeo();// esta funcion del boton es para volver a logearse 
        log.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void consultarhuellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarhuellaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultarhuellaActionPerformed

    /**
     * @param args the command line arguments
     */
   
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the form */
        
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultarhuella;
    private javax.swing.JButton consultarman;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
